# Generated by Django 4.2.5 on 2023-10-13 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileInfo', '0002_userdata_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('quote', models.CharField(max_length=255)),
                ('quote_lv', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='images/logo')),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('linkedin_url', models.URLField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
